### ISSUE TITLE
Support for supplying DDB client

### ISSUE THREAD

**Issue by harlow** [adorechic/rcredstash#11]
Hello, we're looking into integrating rcredstash and running into a few issues here:
https://github.com/adorechic/rcredstash/blob/master/lib/cred_stash/repository.rb#L8

Our test suite is locked down to disallow external HTTP request. We run DDB local during specs, we'd like to be able to inject our own DDB client in that talks to localhost.
https://github.com/adorechic/rcredstash/blob/master/lib/cred_stash/repository/dynamo_db.rb#L4

Any ideas? are you open to a PR with this functionality?

**Comment by adorechic** [comment]
I have an idea to use other storage like PostgreSQL, MySQL, Redis, and so on, so rcredstash has a configure for storage. However I don't implement it yet.

> are you open to a PR with this functionality?

Of course. 
IMO, I think adding `dynamodb_local` as a storage type is a simple way.

```ruby
case CredStash.config.storage
    when :dynamodb
      DynamoDB.new
    when :dynamodb_local
      DynamoDBLocal.new
    else
      ...
```

Do you have another ideas?

**Comment by adorechic** [comment]
BTW, it you use rails, there is an another option.
I use rcredstash via [secret_env](https://github.com/adorechic/secret_env) on rails.
secret_env allows to set variables from credstash in production, and set from file in test or development environments.

**Comment by harlow** [comment]
> Do you have another ideas?

Another option could to allow the codebase to specify a `DYNAMODB_URL` which would be used by the client if provided.

Could look something like this:

```ruby
def initialize(client: nil)
  @client = client || Aws::DynamoDB::Client.new(client_options)
end

# ...

def client_options
  return {} unless ENV['DYNAMODB_URL']
  { endpoint: ENV['DYNAMODB_URL'] }
end
```
