### ISSUE TITLE
Unable to configure AWS region

### ISSUE THREAD

**Issue by nikhilo** [adorechic/rcredstash#18]
I'm want to make credstash data available into Chef. One of the ways would be to fetch the data using a custom Ohai plugin. For AWS credentials, I'm relying on the EC2 Instance IAM role. The problem is I'm not able to set the `AWS_REGION` by any means. Any recommendation on how to get this working?
Here's the error I see,
```
[2020-01-27T11:00:33+00:00] DEBUG: Plugin Credstash threw #<Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']>
```

**Comment by adorechic** [comment]
Hi! AWS SDK for Ruby raises this error. How did you pass the `AWS_REGION` environment variable?

**Comment by nikhilo** [comment]
I wasn't able to "pass" it in the chef-client run or ohai run. Instead I was able to set it inside my script itself like so, `ENV['AWS_REGION'] = ec2["region"]`
And it seems to be working!
