### ISSUE TITLE
Override Default table

### ISSUE THREAD

**Issue by rilindo** [adorechic/rcredstash#3]
How do I use a different table and key for credstash? For example, instead of:

credstash - key
credstash - table

We go with:

credstash_prod - key
credstash_prod - table

This can be done from the cli, but it is not clear how can it be done from this gem.

**Comment by adorechic** [comment]
Do you say about `-t` option? https://github.com/fugue/credstash/#usage

**Comment by rilindo** [comment]
Yes, that is what I mean. It is not clear from code how an alternate table can be used.

**Comment by adorechic** [comment]
Now I supported `table_name` option. b3e886a4cb16002bba2fc4e74dc2f472e4b4a0ee
Please install [v0.4.0](https://rubygems.org/gems/rcredstash/versions/0.4.0) and configure as

``` ruby
CredStash.configure do |config|
  config.table_name = 'your_table_name'
end

CredStash.get(key)
CredStash.put(key, value)

# You don't have to set table_name each method calls while same ruby process.
# If you want to connect another table,  just call `configure` again.
CredStash.configure do |config|
  config.table_name = 'another_table'
end

CredStash.get(key)
```

**Comment by rilindo** [comment]
Thanks!
