### ISSUE TITLE
Ruby 2.0.0 Support

### ISSUE THREAD

**Issue by discreet** [adorechic/rcredstash#5]
Is there any support for Ruby 2.0.0? I see the TravisCI tests are for Ruby 2.2.5 and 2.3.1. The native Ruby on CentOS 7 is 2.0.0 and it would be a lot easier to have support for that then to RVM install a different version and make sure all scripts, etc are using the RVM installed Ruby.

**Comment by adorechic** [comment]
Ruby 2.0.0 has reached [EOL](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), so I don't have any plan to support it.
