### ISSUE TITLE
Encryption Context Support

### ISSUE THREAD

**Issue by discreet** [adorechic/rcredstash#6]
Is there a way to have rcredstash get and put credentials using encryption context? We rely heavily on this feature and from the looks of the 0.5.0 release it is not available.

**Comment by adorechic** [comment]
Current rcredstash does not support encryption context. I have a plan to support it.

**Comment by adorechic** [comment]
@discreet 
Now v0.6.0 supports encryption context. See https://github.com/adorechic/rcredstash#usage

**Comment by discreet** [comment]
@adorechic Awesome! Thank you!
